/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#1e1200',
        'secondary-container': '#2170e4',
        'inverse-on-surface': '#eaf1ff',
        'tertiary-fixed': '#fadfb8',
        'tertiary-fixed-dim': '#ddc39d',
        'surface-container-highest': '#d3e4fe',
        'on-primary-container': '#8590a6',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#45474c',
        background: '#f8f9ff',
        'on-tertiary-container': '#a38c6a',
        error: '#ba1a1a',
        'tertiary-container': '#35260c',
        'on-tertiary-fixed-variant': '#564427',
        'on-primary-fixed': '#111c2d',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#545f73',
        surface: '#f8f9ff',
        'inverse-surface': '#213145',
        secondary: '#0058be',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'secondary-fixed': '#d8e2ff',
        'surface-container-low': '#eff4ff',
        'primary-fixed-dim': '#bcc7de',
        'on-primary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-tertiary-fixed': '#271902',
        'on-secondary-container': '#fefcff',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        'inverse-primary': '#bcc7de',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed-variant': '#3c475a',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#e5eeff',
        'primary-container': '#1e293b',
        primary: '#091426',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#adc6ff',
        accent: '#2170e4',
        mist: '#eef3fb',
        shell: '#f9fbff',
        ink: '#111a31',
        success: '#39b574',
        warning: '#f0c169',
        danger: '#f26f74',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        panel: '0 18px 45px rgba(12, 34, 80, 0.08)',
        soft: '0 8px 24px rgba(14, 30, 67, 0.08)',
      },
      keyframes: {
        rise: {
          '0%': { opacity: '0', transform: 'translateY(18px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        drift: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        rise: 'rise 600ms ease-out both',
        'rise-slow': 'rise 900ms ease-out both',
        drift: 'drift 3.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

